server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        #Ruta para HU1: Simular Crédito
        - id: credit-simulator-service
          uri: lb://credit-simulator-service
          predicates:
            - Path=/api/v1/creditSimulator/**
        #Ruta para HU2: Registrar Usuario
        - id: user-register-service
          uri: lb://user-register-service
          predicates:
            - Path=//api/v1/bankUser/**
        #Ruta para HU3: Solicitar crédito