server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          #Decide si será local o de git
          uri: https://github.com/amigo1975/microsevices-data-project
          search-paths: config-data
  application:
    name: config-service
